name: PHPStan
on: [ push, pull_request ]

jobs:
  code_sniffer:
    name: Code sniffer
    runs-on: ubuntu-latest
    steps:
      - name: Install php
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Download dependencies
        run: composer install --prefer-dist
      - name: Run code sniffer
        run: vendor/bin/phpstan analyse -c ./.phpstan.neon app/